import BoardsKanban from './BoardsKanban';
import BoardsModalStack from './BoardsModalStack';
import type { BoardsViewProps } from './BoardsView.types';

export default function BoardsView({
  boards,
  activeIndex,
  setActiveIndex,
  activeBoard,
  workflowState,
  setWorkflowState,
  isAdding,
  setIsAdding,
  boardName,
  setBoardName,
  boardLimit,
  setBoardLimit,
  dragHighlight,
  setDragHighlight,
  taskName,
  setTaskName,
  taskDescription,
  setTaskDescription,
  taskType,
  setTaskType,
  priority,
  setPriority,
  assignee,
  setAssignee,
  dueDate,
  setDueDate,
  taskId,
  setParent,
  setSetParent,
  showChild,
  setShowChild,
  showChildOf,
  showViewEdgesModal,
  setShowViewEdgesModal,
  edges,
  setEdges,
  boardRefreshKey,
  fromEdgeName,
  setFromEdgeName,
  toEdgeName,
  setToEdgeName,
  isAddingEdge,
  setIsAddingEdge,
  showAddTaskModal,
  setShowAddTaskModal,
  setActiveColumnId,
  editModal,
  setEditModal,
  setCurrentTaskId,
  setBoardRefreshKey,
  setState,
  boardHandlers,
  canEditWorkflows,
  projectId,
  user,
}: BoardsViewProps) {
  return (
    <>
      <BoardsModalStack
        showAddTaskModal={showAddTaskModal}
        setShowAddTaskModal={setShowAddTaskModal}
        showViewEdgesModal={showViewEdgesModal}
        setShowViewEdgesModal={setShowViewEdgesModal}
        editModal={editModal}
        setEditModal={setEditModal}
        setCurrentTaskId={setCurrentTaskId}
        showChild={showChild}
        setShowChild={setShowChild}
        showChildOf={showChildOf}
        taskName={taskName}
        setTaskName={setTaskName}
        taskDescription={taskDescription}
        setTaskDescription={setTaskDescription}
        taskType={taskType}
        setTaskType={setTaskType}
        priority={priority}
        setPriority={setPriority}
        assignee={assignee}
        setAssignee={setAssignee}
        dueDate={dueDate}
        setDueDate={setDueDate}
        taskId={taskId}
        setParent={setParent}
        setSetParent={setSetParent}
        edges={edges}
        workflowState={workflowState}
        projectId={projectId}
        activeBoard={activeBoard}
        setEdges={setEdges}
        isAddingEdge={isAddingEdge}
        setIsAddingEdge={setIsAddingEdge}
        fromEdgeName={fromEdgeName}
        setFromEdgeName={setFromEdgeName}
        toEdgeName={toEdgeName}
        setToEdgeName={setToEdgeName}
        boardHandlers={boardHandlers}
      />
      <BoardsKanban
        boards={boards}
        activeIndex={activeIndex}
        setActiveIndex={setActiveIndex}
        activeBoard={activeBoard}
        workflowState={workflowState}
        setWorkflowState={setWorkflowState}
        dragHighlight={dragHighlight}
        setDragHighlight={setDragHighlight}
        setEdges={setEdges}
        boardRefreshKey={boardRefreshKey}
        setBoardRefreshKey={setBoardRefreshKey}
        setShowAddTaskModal={setShowAddTaskModal}
        setActiveColumnId={setActiveColumnId}
        canEditWorkflows={canEditWorkflows}
        projectId={projectId}
        user={user}
        edges={edges}
        isAdding={isAdding}
        setIsAdding={setIsAdding}
        boardName={boardName}
        setBoardName={setBoardName}
        boardLimit={boardLimit}
        setBoardLimit={setBoardLimit}
        boardHandlers={boardHandlers}
        setState={setState}
        setShowViewEdgesModal={setShowViewEdgesModal}
      />
    </>
  );
}
